# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0020_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeformitem',
            name='freeformType',
            field=models.CharField(choices=[('Paragraph', 'Paragraph'), ('String', 'String'), ('Integer', 'Integer'), ('Real', 'Real')], default='Paragraph', max_length=300),
        ),
    ]
