# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0021_auto_20160203_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeformitem',
            name='freeformType',
            field=models.CharField(choices=[('Paragraph', 'Paragraph'), ('Word', 'Word'), ('Integer', 'Integer'), ('Real', 'Real')], default='Paragraph', max_length=300),
        ),
    ]
