# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0025_auto_20160712_0851'),
        ('peer_review', '0025_auto_20160713_1343'),
    ]

    operations = [
    ]
