# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0027_response_batchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdetail',
            name='status',
            field=models.CharField(choices=[('Not attempted', 'Not attempted'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Not attempted', max_length=20),
        ),
    ]
