# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-14 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0030_auto_20170714_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='docfile',
            new_name='doc_file',
        ),
    ]
