# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0033_auto_20180127_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_review.Label')),
                ('questionOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_review.QuestionOrder')),
            ],
        ),
    ]
