# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0035_auto_20180131_0156')
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlabel',
            name='label',
        ),
        migrations.RemoveField(
            model_name='questionlabel',
            name='questionOrder',
        ),
        migrations.RemoveField(
            model_name='label',
            name='question',
        ),
        migrations.AddField(
            model_name='label',
            name='questionOrder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='peer_review.QuestionOrder'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QuestionLabel',
        ),
    ]
