# Generated by Django 2.0.1 on 2018-03-05 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0036_auto_20180203_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionGrouping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peer_review.QuestionGrouping'),
        ),
        migrations.AlterField(
            model_name='label',
            name='questionOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peer_review.QuestionOrder'),
        ),
        migrations.AlterField(
            model_name='questionorder',
            name='questionGrouping',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peer_review.QuestionGrouping'),
        ),
    ]
